CREATE TABLE event_tests (
id INTEGER AUTOINCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
status VARCHAR(50) NOT NULL DEFAULT 'draft',
revision INTEGER NOT NULL DEFAULT 1,
content VARCHAR,
created_at TIMESTAMP,
updated_at TIMESTAMP
);
