CREATE TABLE comments (
id INTEGER AUTOINCREMENT PRIMARY KEY,
user_id INTEGER NOT NULL,
post_id INTEGER NOT NULL,
content VARCHAR,
is_hidden BOOLEAN DEFAULT FALSE,
created_at TIMESTAMP,
updated_at TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
