CREATE TABLE users (
id INTEGER AUTOINCREMENT PRIMARY KEY,
username VARCHAR(191) NOT NULL UNIQUE,
email VARCHAR(191) NOT NULL UNIQUE,
age INTEGER,
balance DOUBLE NOT NULL DEFAULT 0.0,
is_active BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMP,
updated_at TIMESTAMP
);
